# Generated by Django 3.1.6 on 2021-02-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('man', 'Man'), ('woman', 'Woman'), ('hidden', 'Hidden')], default='hidden', max_length=255),
        ),
    ]
