# Generated by Django 3.1.6 on 2021-02-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0002_auto_20210215_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='title',
            field=models.CharField(default='My title', max_length=255),
        ),
    ]
